// TODO: add factory functions to create settings

const mainSettings = Object.freeze({
  id: {
    key: 'id',
    attr: 'id',
    control: 'input',
    label: 'ID',
    description: '',
    section: 'main',
    valueType: 'string',
    inputType: 'text',
    controlType: 'attribute',
  },
  name: {
    key: 'name',
    attr: 'name',
    control: 'input',
    label: 'Name',
    description: '',
    section: 'main',
    valueType: 'string',
    inputType: 'text',
    controlType: 'attribute',
  },
  value: {
    key: 'value',
    attr: 'value',
    control: 'input',
    label: 'Value',
    description: 'Default value',
    section: 'main',
    valueType: 'string',
    inputType: 'text',
    controlType: 'attribute',
  },
  label: {
    key: 'label',
    attr: 'label',
    control: 'input',
    label: 'Label',
    description: '',
    section: 'main',
    valueType: 'string',
    inputType: 'text',
    controlType: 'attribute',
  },
  hint: {
    key: 'hint',
    attr: 'hint',
    control: 'input',
    label: 'Hint',
    description: '',
    section: 'main',
    valueType: 'string',
    inputType: 'text',
    controlType: 'attribute',
  },
  placeholder: {
    key: 'placeholder',
    attr: 'placeholder',
    control: 'input',
    label: 'Placeholder',
    description: '',
    section: 'main',
    valueType: 'string',
    inputType: 'text',
    controlType: 'attribute',
  },
  customItem: {
    key: 'customItem',
    attr: null,
    control: 'button',
    label: 'Custom item',
    description: '',
    section: 'main',
    valueType: null,
    inputType: null,
    controlType: 'custom',
    handler: () => {},
  },
});

export const settings = Object.freeze({
  ...mainSettings,
});
