import { kameoHelpers } from '@kameo/core';

const { createSettingControl } = kameoHelpers;

export const createSettings = () => ({
  id: createSettingControl({
    key: 'id',
    attr: 'id',
    label: 'Field ID',
    description: 'Unique field ID',
  }),
  name: createSettingControl({
    key: 'name',
    attr: 'name',
    label: 'Name',
    description: 'Name of the form field',
  }),
  label: createSettingControl({
    key: 'label',
    attr: 'label',
    label: 'Label',
    description: `The input's label`,
  }),
  hint: createSettingControl({
    key: 'hint',
    attr: 'hint',
    label: 'Hint',
    description: `The input's hint`,
  }),
  placeholder: createSettingControl({
    key: 'placeholder',
    attr: 'placeholder',
    label: 'Placeholder',
    description: 'Placeholder text to show as a hint when the input is empty',
  }),
  readonly: createSettingControl({
    key: 'readonly',
    attr: 'readonly',
    label: 'Readonly',
    description: 'Makes the input readonly',
    control: 'checkbox',
    valueType: 'boolean',
    section: 'state',
  }),
  disabled: createSettingControl({
    key: 'disabled',
    attr: 'disabled',
    label: 'Disabled',
    description: 'Makes the input disabled',
    control: 'checkbox',
    valueType: 'boolean',
    section: 'state',
  }),
  required: createSettingControl({
    key: 'required',
    attr: 'required',
    label: 'Required',
    description: 'Makes the input a required field',
    control: 'checkbox',
    valueType: 'boolean',
    section: 'validation',
  }),
  size: createSettingControl({
    key: 'size',
    attr: 'size',
    label: 'Size',
    description: `The input's size`,
    control: 'select',
    options: [
      { value: 'small', label: 'Small' },
      { value: 'medium', label: 'Medium' },
      { value: 'large', label: 'Large' },
      { value: 'inherit', label: 'Inherit' },
    ],
    section: 'appearance',
  }),
  appearance: createSettingControl({
    key: 'appearance',
    attr: 'appearance',
    label: 'Appearance',
    description: `The input's visual appearance`,
    control: 'select',
    options: [
      { value: 'filled', label: 'Filled' },
      { value: 'outlined', label: 'Outlined' },
    ],
    section: 'appearance',
  }),
  pill: createSettingControl({
    key: 'pill',
    attr: 'pill',
    label: 'Pill',
    description: 'Draws a pill-style input with rounded edges',
    control: 'checkbox',
    valueType: 'boolean',
    section: 'appearance',
  }),
  clearable: createSettingControl({
    key: 'clearable',
    attr: 'clearable',
    label: 'Clearable',
    description: 'Adds a clear button when the input is not empty',
    control: 'checkbox',
    valueType: 'boolean',
    section: 'appearance',
  }),
  pattern: createSettingControl({
    key: 'pattern',
    attr: 'pattern',
    label: 'Pattern',
    description: 'A regular expression pattern to validate input against',
    section: 'validation',
  }),
  minlength: createSettingControl({
    key: 'minlength',
    attr: 'minlength',
    label: 'Minlength',
    description: 'The minimum length of input that will be considered valid',
    control: 'input',
    inputType: 'number',
    section: 'validation',
  }),
  maxlength: createSettingControl({
    key: 'maxlength',
    attr: 'maxlength',
    label: 'Maxlength',
    description: 'The maximum length of input that will be considered valid',
    control: 'input',
    inputType: 'number',
    section: 'validation',
  }),
  autocapitalize: createSettingControl({
    key: 'autocapitalize',
    attr: 'autocapitalize',
    label: 'Autocapitalize',
    description: 'Controls whether and how text input is automatically capitalized as it is entered by the user',
    control: 'select',
    options: [
      { value: 'off', label: 'Off' },
      { value: 'none', label: 'None' },
      { value: 'on', label: 'On' },
      { value: 'sentences', label: 'Sentences' },
      { value: 'words', label: 'Words' },
      { value: 'characters', label: 'Characters' },
    ],
    section: 'other',
  }),
  autocorrect: createSettingControl({
    key: 'autocorrect',
    attr: 'autocorrect',
    label: 'Autocorrect',
    description: `Indicates whether the browser's autocorrect feature is on or off`,
    control: 'select',
    options: [
      { value: 'off', label: 'Off' },
      { value: 'on', label: 'On' },
    ],
    section: 'other',
  }),
  autofocus: createSettingControl({
    key: 'autofocus',
    attr: 'autofocus',
    label: 'Autofocus',
    description: 'Indicates that the input should receive focus on page load',
    control: 'checkbox',
    valueType: 'boolean',
    section: 'other',
  }),
  enterkeyhint: createSettingControl({
    key: 'enterkeyhint',
    attr: 'enterkeyhint',
    label: 'Enterkeyhint',
    description: 'Used to customize the label or icon of the Enter key on virtual keyboards',
    control: 'select',
    options: [
      { value: 'enter', label: 'Enter' },
      { value: 'done', label: 'Done' },
      { value: 'go', label: 'Go' },
      { value: 'next', label: 'Next' },
      { value: 'previous', label: 'Previous' },
      { value: 'search', label: 'Search' },
      { value: 'send', label: 'Send' },
    ],
    section: 'other',
  }),
  spellcheck: createSettingControl({
    key: 'spellcheck',
    attr: 'spellcheck',
    label: 'Spellcheck',
    description: 'Enables spell checking on the input',
    control: 'checkbox',
    valueType: 'boolean',
    section: 'other',
  }),
  inputmode: createSettingControl({
    key: 'inputmode',
    attr: 'inputmode',
    label: 'Inputmode',
    description: 'Tells the browser what type of data will be entered by the user, allowing it to display the appropriate virtual keyboard on supportive devices',
    control: 'select',
    options: [
      { value: 'none', label: 'None' },
      { value: 'text', label: 'Text' },
      { value: 'decimal', label: 'Decimal' },
      { value: 'numeric', label: 'Numeric' },
      { value: 'tel', label: 'Tel' },
      { value: 'search', label: 'Search' },
      { value: 'email', label: 'Email' },
      { value: 'url', label: 'Url' },
    ],
    section: 'other',
  }),
});
