export const formFields = [
  {
    id: 'formInputText',
    title: 'Text field',
    description: 'Enter info',
    name: 'text',
    fieldType: 'formInputText',
  },
  {
    id: 'formInputName',
    title: 'Name',
    description: 'Enter name',
    name: 'name',
    fieldType: 'formInputName',
  },
  {
    id: 'formInputEmail',
    title: 'Email',
    description: 'Enter email',
    name: 'email',
    fieldType: 'formInputEmail',
  },
  {
    id: 'formInputDate',
    title: 'Date',
    description: 'Date',
    name: 'date',
    fieldType: 'formInputDate',
  },
  {
    id: 'formTextarea',
    title: 'Textarea',
    description: 'Enter text',
    name: 'textarea',
    fieldType: 'formTextarea',
  },
  {
    id: 'formRating',
    title: 'Rating',
    description: 'Rating',
    name: 'rating',
    fieldType: 'formRating',
  },
  {
    id: 'formSubmit',
    title: 'Submit',
    description: 'Submit your form',
    fieldType: 'formSubmit',
  },
];
