export const formFields = [
  {
    id: 'formInputText',
    title: 'Text field',
    description: 'Enter info',
    name: 'text',
    fieldType: 'formInputText',
  },
  {
    id: 'formInputName',
    title: 'Name',
    description: 'Enter name',
    name: 'name',
    fieldType: 'formInputName',
  },
  {
    id: 'formInputEmail',
    title: 'Email',
    description: 'Enter email',
    name: 'email',
    fieldType: 'formInputEmail',
  },
  {
    id: 'formInputNumber',
    title: 'Number',
    description: 'Enter number',
    name: 'date',
    fieldType: 'formInputNumber',
  },
  {
    id: 'formInputDate',
    title: 'Date',
    description: 'Select date',
    name: 'date',
    fieldType: 'formInputDate',
  },
  {
    id: 'formInputTime',
    title: 'Time',
    description: 'Select time',
    name: 'time',
    fieldType: 'formInputTime',
  },
  {
    id: 'formTextarea',
    title: 'Textarea',
    description: 'Enter text',
    name: 'textarea',
    fieldType: 'formTextarea',
  },
  {
    id: 'formCheckbox',
    title: 'Checkbox',
    description: 'Checkbox',
    name: 'checkbox',
    fieldType: 'formCheckbox',
  },
  {
    id: 'formSwitch',
    title: 'Switch',
    description: 'Switch',
    name: 'switch',
    fieldType: 'formSwitch',
  },
  {
    id: 'formRating',
    title: 'Rating',
    description: 'Rating',
    name: 'rating',
    fieldType: 'formRating',
  },
  {
    id: 'formSlider',
    title: 'Slider',
    description: 'Slider',
    name: 'slider',
    fieldType: 'formSlider',
  },
  {
    id: 'formSubmit',
    title: 'Submit',
    description: 'Submit your form',
    fieldType: 'formSubmit',
  },
];
